releaseInfo:
   releaseNotes: "A software update can include, \n • Payment \n - On Account Payment Method Support \n • Report \n - End of Day Report \n - Zero Movement Sales Report \n - Hours And Wages Report \n - ReceivedItems Report"